
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Krishna
 */
public class Bill extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 8835278316144859414L;
	/**
     * Creates new form Bill
     */
    public Bill(String uname) {
        initComponents();
        un = uname;
        
        setSize(875,645);
        table.setFocusable(false);
        table.getTableHeader().setReorderingAllowed(false);
        table.setIntercellSpacing(new java.awt.Dimension(0, 0)); 
        table.getTableHeader().setFont(new Font("Trebuchet MS", Font.BOLD, 14));
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(new Color(75, 190, 237));
        table.getTableHeader().setForeground(new Color(255,255,255));
        table.setRowHeight(25);
        table.setSelectionBackground(new java.awt.Color(75, 190, 237));
        table.setSelectionForeground(new java.awt.Color(255,255,255));
        table.setShowVerticalLines(false);
        table.setShowHorizontalLines(false);
        
        Connection con2;
PreparedStatement ps2;
ResultSet rs2;
try{
	Class.forName("com.mysql.jdbc.Driver");
 con2=DriverManager.getConnection("jdbc:mysql://localhost:3306/palace","root","");
ps2=con2.prepareStatement("select * from bill where username='"+un+"'");
rs2=ps2.executeQuery();
Vector<String> head=new Vector<String>();
ResultSetMetaData rsm=rs2.getMetaData();
int cols=rsm.getColumnCount();

{
head.add("Name");
head.add("Price");
head.add("Type");

}

Vector<Vector<String>> data=new Vector<Vector<String>>();
while(rs2.next())
{
Vector<String> row=new Vector<String>();
for(int i=1;i<=cols;i++)
{
  row.add(rs2.getString(i));
}
data.add(row);
}

table.setModel(new javax.swing.table.DefaultTableModel(
data,head ));
 scrollpane.setViewportView(table);

 
}catch(Exception e)
{
System.out.println(e);
}
        
// Total
try{
	Class.forName("com.mysql.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/palace","root","");
Statement st=con.createStatement();
ResultSet rs=st.executeQuery("Select price from bill where username='"+un+"'");
float tot=0;
while(rs.next())
{
   float p=Float.parseFloat( rs.getString("price"));
     tot=tot+p;
}
txttotal.setText(""+tot);
rs.close();
st.close();
con.close();
    }
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,""+e);
}

//DEcoration Total
try{
	Class.forName("com.mysql.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/palace","root","");
Statement st=con.createStatement();
ResultSet rs=st.executeQuery("Select price from bill where username='"+un+"' and type='Decoration'");
float tot=0;
while(rs.next())
{
   float p=Float.parseFloat( rs.getString("price"));
     tot=tot+p;
}
txtdecoration.setText(""+tot);
        rs.close();
st.close();
con.close();
    }
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,""+e);
}


//Venue Total
try{
	Class.forName("com.mysql.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/palace","root","");
Statement st=con.createStatement();
ResultSet rs=st.executeQuery("Select price from bill where username='"+un+"' and type='Venue'");
float tot=0;
while(rs.next())
{
   float p=Float.parseFloat( rs.getString("price"));
     tot=tot+p;
}
txtvenue.setText(""+tot);
rs.close();
st.close();
con.close();
    }
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,""+e);
}
        
// Food

try{
	Class.forName("com.mysql.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/palace","root","");
Statement st=con.createStatement();
ResultSet rs=st.executeQuery("Select price from bill where username='"+un+"' and type='Food'");
float tot=0;
while(rs.next())
{
   float p=Float.parseFloat( rs.getString("price"));
     tot=tot+p;
}
txtfood.setText(""+tot);
rs.close();
st.close();
con.close();
    }
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,""+e);
}
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollpane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnexit = new javax.swing.JButton();
        txtfood = new javax.swing.JTextField();
        txtvenue = new javax.swing.JTextField();
        txtdecoration = new javax.swing.JTextField();
        p4 = new javax.swing.JPanel();
        l3 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        l2 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        p5 = new javax.swing.JPanel();
        l4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(75, 190, 237));
        jPanel1.setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollpane.setViewportView(table);

        jPanel1.add(scrollpane);
        scrollpane.setBounds(20, 20, 600, 560);

        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit);
        btnexit.setBounds(650, 550, 180, 30);

        txtfood.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtfood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfoodActionPerformed(evt);
            }
        });
        jPanel1.add(txtfood);
        txtfood.setBounds(650, 280, 180, 50);

        txtvenue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvenueActionPerformed(evt);
            }
        });
        jPanel1.add(txtvenue);
        txtvenue.setBounds(650, 200, 180, 50);

        txtdecoration.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtdecoration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdecorationActionPerformed(evt);
            }
        });
        jPanel1.add(txtdecoration);
        txtdecoration.setBounds(650, 120, 180, 50);

        p4.setBackground(new java.awt.Color(120, 204, 238));
        p4.setLayout(null);

        l3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("Food");
        p4.add(l3);
        l3.setBounds(10, 0, 110, 20);

        jPanel1.add(p4);
        p4.setBounds(650, 260, 180, 20);

        p3.setBackground(new java.awt.Color(120, 204, 238));
        p3.setLayout(null);

        l2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setText("Venue");
        p3.add(l2);
        l2.setBounds(10, 0, 110, 20);

        jPanel1.add(p3);
        p3.setBounds(650, 180, 180, 20);

        p2.setBackground(new java.awt.Color(120, 204, 238));
        p2.setLayout(null);

        l1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("Decoration");
        p2.add(l1);
        l1.setBounds(10, 0, 110, 20);

        jPanel1.add(p2);
        p2.setBounds(650, 100, 180, 20);

        txttotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        jPanel1.add(txttotal);
        txttotal.setBounds(650, 360, 180, 50);

        p5.setBackground(new java.awt.Color(120, 204, 238));
        p5.setLayout(null);

        l4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 255, 255));
        l4.setText("Total");
        p5.add(l4);
        l4.setBounds(10, 0, 110, 20);

        jPanel1.add(p5);
        p5.setBounds(650, 340, 180, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 860, 600);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-874)/2, (screenSize.height-641)/2, 874, 641);
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void txtfoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfoodActionPerformed

    private void txtvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvenueActionPerformed

    private void txtdecorationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdecorationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdecorationActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       Bill ob=new Bill("abc");
       ob.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtdecoration;
    private javax.swing.JTextField txtfood;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtvenue;
    // End of variables declaration//GEN-END:variables

   public String un;
   public void saveusername(String uname) {
      un=uname;
    }
}

